#!/usr/bin/env node
/**
 * Plugin template scaffolding — creates a new plugin skeleton.
 *
 * Usage:
 *   node scripts/create-plugin.js <plugin-id> [--name "Display Name"]
 *
 * Example:
 *   node scripts/create-plugin.js memory-forensics --name "Memory Forensics"
 */

import fs from 'fs'
import path from 'path'
import { fileURLToPath } from 'url'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const pluginsDir = path.resolve(__dirname, '..', 'plugins')

function kebabToCamel(s) {
  return s.replace(/-([a-z])/g, (_, c) => c.toUpperCase())
}

function kebabToTitle(s) {
  return s.split('-').map(w => w[0].toUpperCase() + w.slice(1)).join(' ')
}

const args = process.argv.slice(2)
if (args.length === 0 || args[0] === '--help') {
  console.log('Usage: node scripts/create-plugin.js <plugin-id> [--name "Display Name"]')
  process.exit(0)
}

const pluginId = args[0]
const nameIdx = args.indexOf('--name')
const displayName = nameIdx >= 0 && args[nameIdx + 1] ? args[nameIdx + 1] : kebabToTitle(pluginId)
const camelId = kebabToCamel(pluginId)

if (!/^[a-z][a-z0-9-]*$/.test(pluginId)) {
  console.error('Error: plugin-id must be kebab-case (e.g. "my-plugin")')
  process.exit(1)
}

const pluginDir = path.join(pluginsDir, pluginId)

if (fs.existsSync(pluginDir)) {
  console.error(`Error: plugin directory already exists: ${pluginDir}`)
  process.exit(1)
}

fs.mkdirSync(pluginDir, { recursive: true })

// --- index.ts ---
const indexContent = `/**
 * Plugin: ${displayName}
 * Auto-generated by scripts/create-plugin.js
 */

import type { Plugin, PluginServerInterface, PluginToolDeps } from '../../packages/plugin-sdk/src/index.js'

const plugin: Plugin = {
  id: '${pluginId}',
  name: '${displayName}',
  description: 'TODO: describe what this plugin does',
  version: '0.1.0',
  dependencies: [],
  configSchema: [
    // { envVar: 'MY_TOOL_PATH', description: 'Path to external tool', required: false },
  ],

  check() {
    // Return false to skip loading when prerequisites are missing
    return true
  },

  register(server: PluginServerInterface, deps: PluginToolDeps): string[] {
    const tools: string[] = []

    server.registerTool(
      {
        name: '${pluginId}.hello',
        description: '${displayName} — hello world tool',
        inputSchema: {
          type: 'object',
          properties: {
            sample_id: { type: 'string', description: 'Sample ID to analyze' },
          },
          required: ['sample_id'],
        },
      },
      async (args: { sample_id: string }) => ({
        content: [{ type: 'text' as const, text: JSON.stringify({ message: 'Hello from ${displayName}', sample_id: args.sample_id }) }],
      })
    )
    tools.push('${pluginId}.hello')

    return tools
  },

  async teardown() {
    // Cleanup resources if needed
  },
}

export default plugin
`

// --- README.md ---
const readmeContent = `# ${displayName} Plugin

> Auto-generated plugin scaffold — customize as needed.

## Tools

| Tool | Description |
|------|-------------|
| \`${pluginId}.hello\` | Hello world placeholder |

## Configuration

| Env Var | Required | Description |
|---------|----------|-------------|
| *(none yet)* | — | — |

## Development

1. Edit \`plugins/${pluginId}/index.ts\` to add your tools
2. The plugin is auto-discovered on next server start
3. Use \`plugin.list\` MCP tool to verify it loaded
`

fs.writeFileSync(path.join(pluginDir, 'index.ts'), indexContent)
fs.writeFileSync(path.join(pluginDir, 'README.md'), readmeContent)

console.log(`✓ Created plugin scaffold at plugins/${pluginId}/`)
console.log(`  - plugins/${pluginId}/index.ts`)
console.log(`  - plugins/${pluginId}/README.md`)
console.log(`\nNext steps:`)
console.log(`  1. Edit plugins/${pluginId}/index.ts to add your tools`)
console.log(`  2. Restart the server — the plugin is auto-discovered`)
